#!/usr/bin/env python3
"""Generate guru_brain.json with 1000+ entries from templates."""
import json, sys, io, os, copy
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Load existing data
starter = json.load(open('prompts/guru_brain_starter.json', 'r', encoding='utf-8'))
existing = {p['id']: p for p in starter['problems']}

# Load part1 if exists
p1_path = 'resources/knowledge_base/brain_part1.json'
if os.path.exists(p1_path):
    try:
        p1 = json.load(open(p1_path, 'r', encoding='utf-8'))
        for p in p1.get('problems', []):
            if p['id'] not in existing:
                existing[p['id']] = p
    except: pass

print(f"Starting with {len(existing)} existing entries")

# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY TEMPLATES - Each defines problems to generate
# ═══════════════════════════════════════════════════════════════════════════════

CATEGORIES = {
    # ── WINDOWS (80 total, ~60 new needed) ───────────────────────────────────
    "windows": {
        "prefix": "WIN",
        "entries": [
            {"id":"WIN-018","title":"BSOD KERNEL_DATA_INPAGE_ERROR","userSays":["kernel data inpage error","bluescreen kernel","festplattenfehler bluescreen","bsod kernel data","daten seite fehler","bluescreen beim lesen","pc stuerzt ab daten","kernel inpage","festplatte bluescreen","blauer bildschirm kernel error"],"diagnose":["rd_diag_diag-disk","rd_repair_physicaldisk"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"Kritische Events pruefen"},{"step":2,"skill":"rd_repair_physicaldisk","action":"Festplatten-SMART pruefen"},{"step":3,"skill":"rd_diskmgmt_chkdskrun","action":"CHKDSK ausfuehren"},{"step":4,"skill":"rd_repair_sfc","action":"Systemdateien reparieren"},{"step":5,"skill":"rd_diag_diag-disk","action":"Disk-Komplett-Check"}],"erklaerung":"KERNEL_DATA_INPAGE_ERROR bedeutet dass Windows Daten nicht von der Festplatte lesen konnte. Haeufig defekte Sektoren oder sterbende Festplatte.","tags":["bsod","kernel","data","inpage","festplatte","smart","sektoren"],"nachfragen":["Passiert es beim Starten oder waehrend der Arbeit?","Hoeren Sie klickende Geraeusche von der Festplatte?","Wurde die Festplatte kuerzlich gewechselt?"],"hinweis":"Bei SMART-Warnungen sofort Backup empfehlen!"},
            {"id":"WIN-019","title":"BSOD SYSTEM_SERVICE_EXCEPTION","userSays":["system service exception","bsod system service","bluescreen service","system dienst fehler bsod","blauer bildschirm system service exception","bsod ksecdd.sys","bsod ntfs.sys","system service bluescreen","windows absturz service exception","bsod beim spielen"],"diagnose":["rd_repair_evtcrit","rd_drivers_driverfail"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"Stop-Code und Treiber identifizieren"},{"step":2,"skill":"rd_drivers_driverfail","action":"Fehlerhafte Treiber finden"},{"step":3,"skill":"rd_repair_sfc","action":"Systemdateien pruefen"},{"step":4,"skill":"rd_repair_dism","action":"Windows-Image reparieren"},{"step":5,"skill":"rd_gpo_hotfix","action":"Letzte Updates pruefen"}],"erklaerung":"SYSTEM_SERVICE_EXCEPTION wird meist durch fehlerhafte Treiber oder beschaedigte Systemdateien verursacht. Der genannte Dateiname (z.B. ntfs.sys) zeigt die Ursache.","tags":["bsod","system","service","exception","treiber","ntfs","ksecdd"],"nachfragen":["Steht ein Dateiname auf dem Bluescreen?","Seit wann tritt der Fehler auf?","Wurde kuerzlich ein Treiber aktualisiert?"],"hinweis":"Dateiname im BSOD ist der Schluessel zur Loesung."},
            {"id":"WIN-020","title":"BSOD PAGE_FAULT_IN_NONPAGED_AREA","userSays":["page fault in nonpaged area","bsod page fault","speicherfehler bluescreen","ram bluescreen","bsod arbeitsspeicher","bluescreen speicher","page fault nonpaged","windows absturz speicher","ram defekt bluescreen","bsod page fault nonpaged area"],"diagnose":["rd_repair_evtcrit","rd_hw_hwram"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"BSOD-Details auslesen"},{"step":2,"skill":"rd_hw_hwram","action":"RAM-Module pruefen"},{"step":3,"skill":"rd_procs_topram","action":"RAM-Verbrauch analysieren"},{"step":4,"skill":"rd_repair_sfc","action":"Systemdateien reparieren"},{"step":5,"skill":"rd_gpo_hotfix","action":"Updates pruefen"}],"erklaerung":"PAGE_FAULT_IN_NONPAGED_AREA deutet auf defekten RAM oder einen fehlerhaften Treiber hin. Windows versucht auf Speicher zuzugreifen der nicht verfuegbar ist.","tags":["bsod","page","fault","nonpaged","ram","speicher","defekt"],"nachfragen":["Wurde kuerzlich RAM getauscht oder erweitert?","Tritt es bei bestimmten Programmen auf?","Wie alt ist der PC?"],"hinweis":"mdsched.exe (Windows-Speicherdiagnose) empfehlen."},
            {"id":"WIN-021","title":"BSOD DPC_WATCHDOG_VIOLATION","userSays":["dpc watchdog violation","bsod watchdog","bluescreen dpc","pc haengt sich auf watchdog","dpc watchdog bluescreen","windows watchdog fehler","bsod dpc violation","blauer bildschirm watchdog","watchdog timeout","dpc fehler"],"diagnose":["rd_repair_evtcrit","rd_drivers_driverlist"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"Events pruefen"},{"step":2,"skill":"rd_drivers_driverlist","action":"Alle Treiber auflisten"},{"step":3,"skill":"rd_drivers_driverfail","action":"Fehlerhafte Treiber"},{"step":4,"skill":"rd_hw_hwcs","action":"Hardware-Info"},{"step":5,"skill":"rd_repair_sfc","action":"SFC ausfuehren"}],"erklaerung":"DPC_WATCHDOG_VIOLATION bedeutet dass ein Treiber oder eine Hardware zu lange nicht reagiert hat. Oft SSD-Controller oder Netzwerk-Treiber.","tags":["bsod","dpc","watchdog","timeout","treiber","ssd","controller"],"nachfragen":["Wurde kuerzlich eine SSD eingebaut?","Haengt der PC kurz bevor er abstuerzt?","Passiert es bei Netzwerk-Aktivitaet?"],"hinweis":"SSD-Firmware-Update und AHCI-Modus pruefen."},
            {"id":"WIN-022","title":"BSOD WHEA_UNCORRECTABLE_ERROR","userSays":["whea uncorrectable error","bsod whea","hardware fehler bluescreen","bsod hardware","whea bluescreen","uncorrectable error","bluescreen whea","hardware absturz","cpu fehler bluescreen","bsod whea error"],"diagnose":["rd_repair_evtcrit","rd_hw_hwcpu"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"WHEA-Events analysieren"},{"step":2,"skill":"rd_hw_hwcpu","action":"CPU-Info pruefen"},{"step":3,"skill":"rd_hw_hwram","action":"RAM pruefen"},{"step":4,"skill":"rd_diag_diag-hardware","action":"Hardware-Komplett-Check"},{"step":5,"skill":"rd_repair_physicaldisk","action":"Disk-Gesundheit"}],"erklaerung":"WHEA_UNCORRECTABLE_ERROR ist fast immer ein echtes Hardware-Problem - defekte CPU, RAM oder Mainboard. Kann auch durch Ueberhitzung entstehen.","tags":["bsod","whea","hardware","cpu","ram","ueberhitzung","defekt"],"nachfragen":["Wird der PC sehr heiss?","Wurde kuerzlich Hardware getauscht?","Tritt es unter Last auf (Spiele, Rendering)?"],"hinweis":"Bei Ueberhitzung: Luefter pruefen, Waermeleitpaste erneuern."},
            {"id":"WIN-023","title":"BSOD VIDEO_TDR_FAILURE","userSays":["video tdr failure","bsod grafikkarte","bluescreen video","gpu absturz","bluescreen beim spielen","nvlddmkm.sys","atikmpag.sys","grafiktreiber absturz","video tdr","bsod nvidia","bsod amd grafik"],"diagnose":["rd_repair_evtcrit","rd_hw_hwgpu"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"Video-Events pruefen"},{"step":2,"skill":"rd_hw_hwgpu","action":"GPU-Info auslesen"},{"step":3,"skill":"rd_drivers_driverlist","action":"Grafiktreiber Version"},{"step":4,"skill":"rd_drivers_driverupdate","action":"Treiber aktualisieren"},{"step":5,"skill":"rd_sysconfig_powerhigh","action":"Hochleistungs-Energieplan"}],"erklaerung":"VIDEO_TDR_FAILURE bedeutet dass die Grafikkarte nicht rechtzeitig reagiert hat. Meist Treiber-Problem, seltener defekte GPU.","tags":["bsod","video","tdr","gpu","grafikkarte","nvidia","amd","treiber"],"nachfragen":["Welche Grafikkarte ist verbaut?","Tritt es bei Spielen oder Videos auf?","Wurde der Treiber kuerzlich aktualisiert?"],"hinweis":"nvlddmkm.sys = Nvidia, atikmpag.sys = AMD."},
            {"id":"WIN-024","title":"BSOD MEMORY_MANAGEMENT","userSays":["memory management bsod","bluescreen speicherverwaltung","bsod memory","speicher management fehler","windows absturz memory management","bsod ram voll","bluescreen memory","speicherfehler windows","memory management blau","ram management bsod"],"diagnose":["rd_repair_evtcrit","rd_hw_hwram","rd_procs_topram"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"Events analysieren"},{"step":2,"skill":"rd_hw_hwram","action":"RAM-Module Details"},{"step":3,"skill":"rd_procs_topram","action":"RAM-Verbrauch"},{"step":4,"skill":"rd_repair_sfc","action":"Systemdateien reparieren"},{"step":5,"skill":"rd_repair_dism","action":"Image reparieren"}],"erklaerung":"MEMORY_MANAGEMENT zeigt Probleme mit der Speicherverwaltung. Kann defekter RAM, Treiber oder beschaedigte Systemdateien sein.","tags":["bsod","memory","management","ram","speicher","verwaltung"],"nachfragen":["Seit wann tritt es auf?","Wurde RAM gewechselt?","Bei welcher Aktion passiert es?"],"hinweis":"mdsched.exe starten, SFC + DISM ausfuehren."},
            {"id":"WIN-025","title":"BSOD CRITICAL_PROCESS_DIED","userSays":["critical process died","bsod critical process","wichtiger prozess beendet","bluescreen critical","windows startet nicht critical process","bsod nach update critical","critical process died bluescreen","pc startet neu critical process","windows 11 critical process died","critical process fehler"],"diagnose":["rd_repair_evtcrit","rd_repair_sfc"],"skillChain":[{"step":1,"skill":"rd_repair_evtcrit","action":"Welcher Prozess ist abgestuerzt?"},{"step":2,"skill":"rd_repair_sfc","action":"Systemdateien pruefen"},{"step":3,"skill":"rd_repair_dism","action":"Windows-Image reparieren"},{"step":4,"skill":"rd_gpo_hotfix","action":"Letzte Updates pruefen"},{"step":5,"skill":"rd_procs_autostart","action":"Autostart pruefen"}],"erklaerung":"CRITICAL_PROCESS_DIED bedeutet dass ein fuer Windows essentieller Prozess unerwartet beendet wurde. Oft durch beschaedigte Systemdateien oder fehlerhafte Updates.","tags":["bsod","critical","process","died","systemdatei","update","prozess"],"nachfragen":["Gab es kuerzlich ein Windows Update?","Startet Windows im abgesicherten Modus?","Wurde Software installiert/deinstalliert?"],"hinweis":"Im Safe Mode SFC+DISM ausfuehren, letztes Update ggf. deinstallieren."},
            {"id":"WIN-026","title":"Windows Startmenue funktioniert nicht","userSays":["startmenue geht nicht","startmenue oeffnet nicht","start button reagiert nicht","startmenue defekt","windows start klicken passiert nichts","start menue spinnt","startmenue friert ein","windows taste funktioniert nicht","startmenü kaputt","start geht nicht auf","startmenue haengt","kann startmenue nicht oeffnen"],"diagnose":["rd_repair_evtsys","rd_procs_topcpu"],"skillChain":[{"step":1,"skill":"rd_explorer_explorerrestart","action":"Explorer neustarten"},{"step":2,"skill":"rd_appcache_wincachefull","action":"Windows-Cache leeren"},{"step":3,"skill":"rd_repair_sfc","action":"Systemdateien pruefen"},{"step":4,"skill":"rd_appcache_storereset","action":"Store zuruecksetzen"},{"step":5,"skill":"rd_repair_dism","action":"Windows-Image reparieren"}],"erklaerung":"Ein defektes Startmenue liegt oft an beschaedigtem Cache oder defekten Store-Apps. Explorer-Neustart hilft haeufig sofort.","tags":["startmenue","start","button","explorer","cache","store","windows"],"nachfragen":["Seit wann geht es nicht?","Funktioniert die Suche auch nicht?","Wurde kuerzlich ein Update installiert?"],"hinweis":"Explorer-Neustart ist die schnellste Loesung."},
            {"id":"WIN-027","title":"Windows Suche findet nichts","userSays":["suche findet nichts","windows suche kaputt","suche funktioniert nicht","suchleiste leer","cortana findet nichts","nichts gefunden bei suche","windows suche defekt","suche zeigt keine ergebnisse","suchindex kaputt","taskleiste suche geht nicht","kann nichts suchen","suchfunktion geht nicht"],"diagnose":["rd_repair_evtsys"],"skillChain":[{"step":1,"skill":"rd_appcache_searchreset","action":"Such-Index zuruecksetzen"},{"step":2,"skill":"rd_explorer_explorerrestart","action":"Explorer neustarten"},{"step":3,"skill":"rd_repair_sfc","action":"Systemdateien pruefen"},{"step":4,"skill":"rd_appcache_storereset","action":"Store-Reset"}],"erklaerung":"Die Windows-Suche basiert auf einem Index. Wenn der Index beschaedigt ist, findet die Suche nichts mehr. Ein Reset des Index behebt das Problem.","tags":["suche","search","index","cortana","finden","suchleiste","suchfunktion"],"nachfragen":["Findet die Suche gar nichts oder nur bestimmte Dateien nicht?","Seit wann besteht das Problem?","Wurde der PC kuerzlich neu aufgesetzt?"],"hinweis":"WSearch-Dienst und Index zuruecksetzen."},
            {"id":"WIN-028","title":"Windows Kontextmenue langsam","userSays":["rechtsklick langsam","kontextmenue braucht ewig","rechte maustaste haengt","kontextmenue dauert","rechtsklick einfrieren","kontextmenue langsam win11","altes kontextmenue win11","rechtsklick wartezeit","kontextmenue reagiert nicht","desktop rechtsklick langsam"],"diagnose":["rd_procs_topcpu"],"skillChain":[{"step":1,"skill":"rd_explorer_explorerrestart","action":"Explorer neustarten"},{"step":2,"skill":"rd_appcache_wincachefull","action":"Cache bereinigen"},{"step":3,"skill":"rd_repair_sfc","action":"Systemdateien pruefen"}],"erklaerung":"Ein langsames Kontextmenue wird oft durch fehlerhafte Shell-Extensions verursacht. Win11 hat ein neues Kontextmenue das manchmal langsam ist.","tags":["kontextmenue","rechtsklick","langsam","shell","extension","win11"],"nachfragen":["Windows 10 oder 11?","Ueberall langsam oder nur auf dem Desktop?","Wurden kuerzlich Programme installiert?"],"hinweis":"Bei Win11: Registry-Key fuer klassisches Kontextmenue setzen."},
            {"id":"WIN-029","title":"Bildschirmschoner funktioniert nicht","userSays":["bildschirmschoner geht nicht","screensaver funktioniert nicht","bildschirm sperrt nicht","pc sperrt sich nicht","automatische sperre geht nicht","lock screen kommt nicht","bildschirmschoner fehlt","bildschirmschoner einrichten","pc bleibt entsperrt","sperre nach inaktivitaet"],"diagnose":["rd_sysconfig_powerplan"],"skillChain":[{"step":1,"skill":"rd_sysconfig_locktime","action":"Sperrbildschirm-Timeout pruefen"},{"step":2,"skill":"rd_sysconfig_powerplan","action":"Energieplan pruefen"},{"step":3,"skill":"rd_gpo_gpresult","action":"Gruppenrichtlinien pruefen"}],"erklaerung":"Der Bildschirmschoner wird ueber Energieoptionen und Gruppenrichtlinien gesteuert. Oft ueberschreibt eine GPO die lokalen Einstellungen.","tags":["bildschirmschoner","screensaver","sperre","lock","timeout","inaktivitaet"],"nachfragen":["Soll der PC sich sperren oder einen Screensaver zeigen?","Ist der PC in einer Domaene?","Nach wie vielen Minuten soll gesperrt werden?"],"hinweis":"GPO kann lokale Einstellungen ueberschreiben."},
            {"id":"WIN-030","title":"Windows Sandbox/Hyper-V aktivieren","userSays":["sandbox aktivieren","hyper-v aktivieren","hyper v geht nicht","windows sandbox einrichten","virtualisierung aktivieren","hypervisor fehlt","sandbox nicht verfuegbar","hyper-v installieren","vm erstellen windows","wsl installieren","linux auf windows"],"diagnose":["rd_hw_hwcpu","rd_hw_hwcs"],"skillChain":[{"step":1,"skill":"rd_hw_hwcpu","action":"CPU-Virtualisierung pruefen"},{"step":2,"skill":"rd_hw_hwcs","action":"System-Info (Pro/Enterprise?)"},{"step":3,"skill":"rd_gpo_gpresult","action":"Richtlinien pruefen"}],"erklaerung":"Windows Sandbox und Hyper-V benoetigen CPU-Virtualisierung (VT-x/AMD-V) und Windows Pro oder Enterprise. Die Virtualisierung muss im BIOS aktiviert sein.","tags":["sandbox","hyper-v","virtualisierung","wsl","linux","vm","bios"],"nachfragen":["Welche Windows-Edition (Home/Pro/Enterprise)?","Ist Virtualisierung im BIOS aktiviert?","Was genau wollen Sie virtualisieren?"],"hinweis":"Home-Edition hat kein Hyper-V, nur WSL2."},
        ]
    },
    # ── OUTLOOK (60 total) ───────────────────────────────────────────────────
    "outlook": {
        "prefix": "OUT",
        "entries": [
            {"id":"OUT-008","title":"Outlook AutoDiscover funktioniert nicht","userSays":["autodiscover fehler","outlook findet server nicht","exchange server nicht gefunden","autodiscover outlook","konto automatisch einrichten geht nicht","outlook autodiscover","server einstellungen werden nicht gefunden","exchange autodiscover problem","outlook konto einrichten fehler","autodiscover xml fehler"],"diagnose":["rd_net_nslookup","rd_net_testport"],"skillChain":[{"step":1,"skill":"rd_net_nslookup","action":"AutoDiscover DNS pruefen"},{"step":2,"skill":"rd_net_testport","action":"Exchange-Port 443 testen"},{"step":3,"skill":"rd_appcache_credclear","action":"Gespeicherte Anmeldedaten loeschen"},{"step":4,"skill":"rd_appcache_outlookrepair","action":"Outlook-Profil reparieren"}],"erklaerung":"AutoDiscover findet automatisch die Exchange-Server-Einstellungen. Wenn es nicht funktioniert, kann Outlook kein Konto einrichten.","tags":["autodiscover","exchange","server","konto","einrichten","dns"],"nachfragen":["Neues Konto oder bestehendes?","Firmen-Mail oder privat?","Gibt es eine Fehlermeldung?"],"hinweis":"DNS-Eintrag _autodiscover._tcp pruefen."},
            {"id":"OUT-009","title":"Outlook Regeln funktionieren nicht","userSays":["outlook regeln gehen nicht","regeln funktionieren nicht","e-mail regeln greifen nicht","posteingangsregeln defekt","outlook regel wird nicht ausgefuehrt","mails werden nicht sortiert","automatische sortierung geht nicht","regel verschiebt nicht","outlook filter funktioniert nicht","regeln werden ignoriert"],"diagnose":["rd_diag_diag-outlook"],"skillChain":[{"step":1,"skill":"rd_diag_diag-outlook","action":"Outlook-Gesundheit pruefen"},{"step":2,"skill":"rd_appcache_outlookrepair","action":"Outlook /cleanrules ausfuehren"},{"step":3,"skill":"rd_appcache_outlookcache","action":"OST-Cache zuruecksetzen"}],"erklaerung":"Outlook-Regeln koennen durch beschaedigte Regelndateien oder OST-Probleme aufhoeren zu funktionieren. Ein Regel-Reset behebt das meist.","tags":["regeln","rules","filter","sortierung","posteingang","automatisch"],"nachfragen":["Seit wann funktionieren die Regeln nicht?","Alle Regeln oder bestimmte?","Werden E-Mails ueberhaupt noch empfangen?"],"hinweis":"Outlook /cleanrules setzt alle Regeln zurueck - User vorher warnen!"},
            {"id":"OUT-010","title":"Outlook Signatur verschwindet","userSays":["signatur weg","outlook signatur fehlt","signatur wird nicht angezeigt","e-mail signatur verschwunden","signatur nach update weg","outlook zeigt keine signatur","signatur immer wieder weg","neue signatur erstellen","signatur einrichten","outlook signatur wiederherstellen"],"diagnose":["rd_diag_diag-outlook"],"skillChain":[{"step":1,"skill":"rd_diag_diag-outlook","action":"Outlook-Profil pruefen"},{"step":2,"skill":"rd_fileops_dirlist","action":"Signatur-Ordner pruefen"},{"step":3,"skill":"rd_appcache_outlookrepair","action":"Outlook-Profil reparieren"}],"erklaerung":"Signaturen werden lokal im Outlook-Profil gespeichert. Nach einem Profil-Reset oder Update koennen sie verschwinden.","tags":["signatur","signature","unterschrift","email","profil","verschwunden"],"nachfragen":["War die Signatur vorher vorhanden?","Nutzen Sie eine zentral verwaltete Signatur?","Wurde Outlook kuerzlich repariert?"],"hinweis":"Signatur-Ordner: AppData/Roaming/Microsoft/Signatures"},
            {"id":"OUT-011","title":"Outlook Anhaenge koennen nicht geoeffnet werden","userSays":["anhang oeffnet nicht","outlook anhang fehler","kann anhang nicht oeffnen","datei im anhang geht nicht","outlook blockiert anhang","anhang wird nicht angezeigt","winmail.dat statt anhang","anhang zu gross","outlook anhaenge problem","email anhang laesst sich nicht oeffnen","anlage kann nicht geoeffnet werden"],"diagnose":["rd_diag_diag-outlook"],"skillChain":[{"step":1,"skill":"rd_diag_diag-outlook","action":"Outlook-Status pruefen"},{"step":2,"skill":"rd_appcache_outlookrepair","action":"Outlook reparieren"},{"step":3,"skill":"rd_appcache_wincachefull","action":"Temp-Dateien bereinigen"}],"erklaerung":"Outlook blockiert bestimmte Dateitypen aus Sicherheitsgruenden. Winmail.dat entsteht wenn RTF-Format statt HTML verwendet wird.","tags":["anhang","attachment","datei","winmail","blockiert","oeffnen","anlage"],"nachfragen":["Welcher Dateityp (.exe, .zip, .pdf)?","Kommt eine Fehlermeldung?","Winmail.dat oder normaler Anhang?"],"hinweis":"Registry Level1Remove fuer blockierte Dateitypen."},
            {"id":"OUT-012","title":"Outlook Postfach voll","userSays":["postfach voll","mailbox voll","outlook speicher voll","kann keine mails mehr senden","postfach speicherplatz","mailbox quota erreicht","outlook meldet postfach voll","e-mail speicher aufgebraucht","outlook quota","zu wenig speicher outlook"],"diagnose":["rd_diag_diag-outlook"],"skillChain":[{"step":1,"skill":"rd_diag_diag-outlook","action":"OST-Groesse und Postfach pruefen"},{"step":2,"skill":"rd_appcache_outlookcache","action":"OST komprimieren"},{"step":3,"skill":"rd_appcache_wincachefull","action":"Temp-Dateien bereinigen"}],"erklaerung":"Exchange-Postfaecher haben ein Speicherlimit (Quota). Bei Ueberschreitung kann man keine Mails mehr senden. Alte Mails loeschen oder archivieren.","tags":["postfach","voll","quota","speicher","mailbox","limit","archiv"],"nachfragen":["Wie gross ist das Postfach aktuell?","Gibt es ein Online-Archiv?","Koennen alte Mails geloescht werden?"],"hinweis":"Online-Archiv in M365 aktivieren wenn verfuegbar."},
            {"id":"OUT-013","title":"Outlook Shared Mailbox hinzufuegen","userSays":["shared mailbox hinzufuegen","gemeinsames postfach einrichten","funktionspostfach oeffnen","geteiltes postfach outlook","shared mailbox outlook","info postfach hinzufuegen","gruppen postfach einrichten","zweites postfach oeffnen","zusaetzliches postfach","shared mailbox funktioniert nicht"],"diagnose":["rd_diag_diag-outlook"],"skillChain":[{"step":1,"skill":"rd_diag_diag-outlook","action":"Outlook-Status pruefen"},{"step":2,"skill":"rd_appcache_authreset","action":"Authentifizierung erneuern"},{"step":3,"skill":"rd_appcache_outlookrepair","action":"Outlook-Profil reparieren"}],"erklaerung":"Shared Mailboxes werden ueber AutoDiscover automatisch eingebunden wenn die Berechtigung im Exchange gesetzt ist. Manchmal dauert die Replikation.","tags":["shared","mailbox","postfach","gemeinsam","funktionspostfach","delegiert"],"nachfragen":["Haben Sie Berechtigung auf das Postfach?","Soll es automatisch oder manuell eingebunden werden?","Exchange Online oder On-Premises?"],"hinweis":"Berechtigung im Exchange Admin Center pruefen."},
        ]
    },
    # ── TEAMS (50 total) ─────────────────────────────────────────────────────
    "teams": {
        "prefix": "TEAMS",
        "entries": [
            {"id":"TEAMS-005","title":"Teams Besprechung beitreten fehlgeschlagen","userSays":["kann meeting nicht beitreten","teams meeting geht nicht","besprechung beitreten fehler","meeting link funktioniert nicht","teams meeting teilnehmen geht nicht","kann nicht in besprechung","meeting startet nicht","teams konferenz fehler","besprechung laesst sich nicht oeffnen","meeting beitreten klappt nicht"],"diagnose":["rd_diag_diag-teams","rd_diag_diag-network"],"skillChain":[{"step":1,"skill":"rd_diag_diag-teams","action":"Teams-Status pruefen"},{"step":2,"skill":"rd_diag_diag-network","action":"Netzwerk pruefen"},{"step":3,"skill":"rd_appcache_teamscache","action":"Teams-Cache loeschen"},{"step":4,"skill":"rd_appcache_credclear","action":"Anmeldedaten loeschen"}],"erklaerung":"Meeting-Beitritt kann an Cache, Netzwerk oder Authentifizierung scheitern. Cache-Reset und Neuanmeldung helfen meist.","tags":["meeting","besprechung","beitreten","konferenz","link","teams"],"nachfragen":["Internes oder externes Meeting?","Browser oder Desktop-App?","Kommt eine Fehlermeldung?"],"hinweis":"Externe Meetings benoetigen ggf. Gastzugang."},
            {"id":"TEAMS-006","title":"Teams Benachrichtigungen kommen nicht","userSays":["teams benachrichtigungen fehlen","teams notifications gehen nicht","keine teams benachrichtigung","teams meldet sich nicht","neue nachrichten werden nicht angezeigt","teams popup fehlt","teams benachrichtigung aus","keine push benachrichtigung teams","teams zeigt neue nachrichten nicht","stille benachrichtigungen teams"],"diagnose":["rd_diag_diag-teams"],"skillChain":[{"step":1,"skill":"rd_diag_diag-teams","action":"Teams-Status pruefen"},{"step":2,"skill":"rd_appcache_teamscache","action":"Teams-Cache loeschen"},{"step":3,"skill":"rd_sysconfig_powerplan","action":"Fokus-Assist pruefen"}],"erklaerung":"Benachrichtigungen koennen durch Fokus-Assist, DND-Modus oder Cache-Probleme unterdrueckt werden.","tags":["benachrichtigung","notification","push","popup","stille","teams"],"nachfragen":["Ist Nicht-Stoeren aktiviert?","Desktop oder Mobil?","Nur bei bestimmten Chats?"],"hinweis":"Windows Fokus-Assist blockt Teams-Notifications."},
            {"id":"TEAMS-007","title":"Teams hohe CPU-Auslastung","userSays":["teams cpu hoch","teams frisst cpu","teams macht pc langsam","teams verbraucht zu viel","teams ressourcen","teams performance schlecht","teams langsam cpu","microsoft teams cpu auslastung","teams bremst pc","teams hoher verbrauch"],"diagnose":["rd_diag_diag-teams","rd_procs_topcpu"],"skillChain":[{"step":1,"skill":"rd_procs_topcpu","action":"CPU-Verbrauch analysieren"},{"step":2,"skill":"rd_diag_diag-teams","action":"Teams-Gesundheit pruefen"},{"step":3,"skill":"rd_appcache_teamscache","action":"Teams-Cache loeschen"},{"step":4,"skill":"rd_sysconfig_powerhigh","action":"Hochleistungs-Energieplan"}],"erklaerung":"Teams kann bei grossem Cache oder vielen offenen Chats sehr CPU-intensiv werden. Cache-Reset und Hardware-Beschleunigung pruefen.","tags":["cpu","performance","langsam","auslastung","ressourcen","teams","verbrauch"],"nachfragen":["Wie viel CPU verbraucht Teams?","Wie viele Chats/Teams sind offen?","Ist der PC generell langsam?"],"hinweis":"Hardware-Beschleunigung in Teams-Einstellungen pruefen."},
            {"id":"TEAMS-008","title":"Teams Dateien hochladen fehlgeschlagen","userSays":["teams datei hochladen geht nicht","upload teams fehler","datei senden teams geht nicht","teams upload fehlgeschlagen","kann keine datei in teams teilen","teams datei freigeben fehler","datei zu gross teams","teams sharepoint upload fehler","teams datei wird nicht hochgeladen","upload in teams haengt"],"diagnose":["rd_diag_diag-teams","rd_diag_diag-network"],"skillChain":[{"step":1,"skill":"rd_diag_diag-network","action":"Netzwerk pruefen"},{"step":2,"skill":"rd_diag_diag-teams","action":"Teams-Status pruefen"},{"step":3,"skill":"rd_appcache_teamscache","action":"Teams-Cache loeschen"},{"step":4,"skill":"rd_zscaler_zscstatus","action":"Zscaler pruefen"}],"erklaerung":"Datei-Upload in Teams nutzt SharePoint im Hintergrund. Netzwerk-Probleme, Proxy oder Dateibeschraenkungen koennen den Upload blockieren.","tags":["upload","datei","hochladen","sharepoint","teams","freigabe"],"nachfragen":["Wie gross ist die Datei?","Welcher Dateityp?","Funktioniert SharePoint im Browser?"],"hinweis":"Max Upload-Groesse: 250GB in Teams."},
        ]
    },
    # ── OFFICE ────────────────────────────────────────────────────────────────
    "office": {"prefix": "OFF", "entries": [
        {"id":"OFF-003","title":"Excel Makros deaktiviert","userSays":["excel makros gehen nicht","makros deaktiviert","excel blockiert makros","vba geht nicht","makrosicherheit","excel makro wird nicht ausgefuehrt","enable macros excel","makros aktivieren","trusted locations","makro gesperrt"],"diagnose":["rd_software_swlist"],"skillChain":[{"step":1,"skill":"rd_gpo_gpresult","action":"Makro-Richtlinien pruefen"},{"step":2,"skill":"rd_software_swlist","action":"Office-Version pruefen"},{"step":3,"skill":"rd_appcache_officequick","action":"Office reparieren"}],"erklaerung":"Makros werden aus Sicherheitsgruenden oft per Gruppenrichtlinie blockiert. Trusted Locations oder digitale Signaturen sind die sichere Loesung.","tags":["makro","macro","vba","deaktiviert","sicherheit","excel","blockiert"],"nachfragen":["Firmeneigene oder externe Makros?","Kommt eine Sicherheitswarnung?","Welche Excel-Version?"],"hinweis":"Trusted Locations statt generelles Aktivieren empfehlen."},
        {"id":"OFF-004","title":"Word Vorlage defekt","userSays":["word vorlage kaputt","normal.dotm beschaedigt","word formatierung spinnt","word startet komisch","word vorlage zuruecksetzen","standard vorlage word defekt","word template problem","normal.dotm loeschen","word oeffnet mit falscher vorlage","word formatvorlagen kaputt"],"diagnose":["rd_software_swlist"],"skillChain":[{"step":1,"skill":"rd_fileops_dirlist","action":"Normal.dotm suchen"},{"step":2,"skill":"rd_fileops_filerename","action":"Normal.dotm umbenennen"},{"step":3,"skill":"rd_appcache_officequick","action":"Office Schnellreparatur"}],"erklaerung":"Die Normal.dotm ist die Standard-Vorlage von Word. Wenn sie beschaedigt ist, spinnt Word bei jedem Dokument. Umbenennen erzwingt Neuerstellung.","tags":["vorlage","template","normal","dotm","formatierung","word","standard"],"nachfragen":["Betrifft es alle Dokumente oder nur eines?","Wurde die Vorlage angepasst?","Haben andere User das gleiche Problem?"],"hinweis":"Normal.dotm liegt unter AppData/Roaming/Microsoft/Templates."},
        {"id":"OFF-005","title":"PowerPoint Video/Audio funktioniert nicht","userSays":["powerpoint video geht nicht","praesentation kein ton","powerpoint audio fehlt","video in powerpoint spielt nicht","eingebettetes video geht nicht","powerpoint medien fehler","praesentation video abspielen","powerpoint kein sound","multimedia powerpoint problem","video powerpoint schwarz"],"diagnose":["rd_software_swlist"],"skillChain":[{"step":1,"skill":"rd_software_swlist","action":"Office-Version und Codecs pruefen"},{"step":2,"skill":"rd_appcache_officequick","action":"Office reparieren"},{"step":3,"skill":"rd_audio_audiodevall","action":"Audio-Geraete pruefen"}],"erklaerung":"Videos in PowerPoint benoetigen die richtigen Codecs. Eingebettete Videos funktionieren besser als verlinkte. MP4 mit H.264 ist das sicherste Format.","tags":["powerpoint","video","audio","medien","praesentation","abspielen","codec"],"nachfragen":["Eingebettetes oder verlinktes Video?","Welches Video-Format?","Funktioniert Audio in anderen Programmen?"],"hinweis":"MP4/H.264 verwenden fuer beste Kompatibilitaet."},
    ]},
    # ── DRUCKER ───────────────────────────────────────────────────────────────
    "drucker": {"prefix": "PRN", "entries": [
        {"id":"PRN-004","title":"Drucker druckt doppelte Seiten","userSays":["drucker druckt doppelt","doppelte ausdrucke","jede seite zweimal","drucker druckt alles doppelt","mehrere kopien drucker","drucker druckt 2 mal","doppeldruck","seiten kommen doppelt raus","drucker gibt zwei exemplare aus","ungewollte kopien"],"diagnose":["rd_printer_getprinter","rd_printer_printjobs"],"skillChain":[{"step":1,"skill":"rd_printer_printjobs","action":"Warteschlange pruefen"},{"step":2,"skill":"rd_printer_getprinter","action":"Drucker-Einstellungen"},{"step":3,"skill":"rd_printer_clearjobs","action":"Warteschlange leeren"},{"step":4,"skill":"rd_printer_spooler","action":"Spooler neustarten"}],"erklaerung":"Doppelte Ausdrucke entstehen meist durch doppelte Druckauftraege in der Warteschlange oder falsche Kopien-Einstellung im Treiber.","tags":["doppelt","kopien","doppeldruck","seiten","drucker","mehrfach"],"nachfragen":["Aus welchem Programm drucken Sie?","Steht Kopien auf 1?","Nur bei diesem Drucker?"],"hinweis":"Kopien-Einstellung im Treiber UND in der Anwendung pruefen."},
        {"id":"PRN-005","title":"Drucker Farbe funktioniert nicht","userSays":["drucker druckt nur schwarz weiss","keine farbe","farbdruck geht nicht","drucker druckt ohne farbe","farbe fehlt beim drucken","nur graustufen","drucker farbe defekt","farbpatrone leer","drucker druckt nicht in farbe","schwarz weiss statt farbe"],"diagnose":["rd_printer_getprinter"],"skillChain":[{"step":1,"skill":"rd_printer_getprinter","action":"Drucker-Konfiguration pruefen"},{"step":2,"skill":"rd_diag_diag-printer","action":"Drucker-Komplett-Check"},{"step":3,"skill":"rd_printer_spooler","action":"Spooler neustarten"}],"erklaerung":"Farbdruck kann in den Drucker-Eigenschaften, im Treiber oder per GPO auf Schwarz-Weiss eingestellt sein. Auch leere Farbpatronen verursachen das.","tags":["farbe","schwarz","weiss","graustufen","farbdruck","patrone","toner"],"nachfragen":["Firmendrucker oder eigener?","Wird Farbe per Richtlinie gesperrt?","Sind Patronen/Toner voll?"],"hinweis":"Follow-Me Drucker haben oft Farbsperre per Default."},
        {"id":"PRN-006","title":"Drucker Papierstau","userSays":["papierstau","papier steckt fest","drucker zeigt papierstau","paper jam","drucker papierstau meldung","papier klemmt","drucker zieht papier nicht","papierstau obwohl kein papier","drucker meldet stau","papierstau beheben"],"diagnose":["rd_diag_diag-printer"],"skillChain":[{"step":1,"skill":"rd_diag_diag-printer","action":"Drucker-Status pruefen"},{"step":2,"skill":"rd_printer_spooler","action":"Spooler neustarten"},{"step":3,"skill":"rd_printer_clearjobs","action":"Warteschlange leeren"}],"erklaerung":"Papierstaus koennen auch nach Entfernung des Papiers als Meldung bleiben. Spooler-Neustart und Drucker aus/ein hilft.","tags":["papierstau","papier","stau","jam","klemmt","drucker"],"nachfragen":["Wurde das Papier bereits entfernt?","Zeigt der Drucker noch den Stau an?","Welches Fach wird verwendet?"],"hinweis":"Drucker komplett aus und wieder einschalten nach Papier-Entfernung."},
    ]},
    # ── NETZWERK ──────────────────────────────────────────────────────────────
    "netzwerk": {"prefix": "NET", "entries": [
        {"id":"NET-006","title":"DNS-Server antwortet nicht","userSays":["dns server antwortet nicht","dns fehler","seite nicht gefunden dns","dns problem","dns geht nicht","nslookup fehler","dns aufloesung fehlgeschlagen","dns server nicht erreichbar","webseiten laden nicht dns","name resolution fehler"],"diagnose":["rd_net_nslookup","rd_net_flushdns"],"skillChain":[{"step":1,"skill":"rd_net_nslookup","action":"DNS-Aufloesung testen"},{"step":2,"skill":"rd_net_flushdns","action":"DNS-Cache leeren"},{"step":3,"skill":"rd_net_ipconfig","action":"DNS-Server-Konfiguration pruefen"},{"step":4,"skill":"rd_appcache_netreset","action":"Netzwerk komplett zuruecksetzen"}],"erklaerung":"DNS uebersetzt Webseiten-Namen in IP-Adressen. Wenn der DNS-Server nicht antwortet, koennen keine Webseiten geoeffnet werden, obwohl das Internet funktioniert.","tags":["dns","server","aufloesung","nslookup","name","resolution"],"nachfragen":["Funktioniert Ping auf 8.8.8.8?","Welcher DNS-Server ist eingestellt?","Betrifft es alle Seiten?"],"hinweis":"Ping auf IP geht, aber Webseiten nicht = DNS-Problem."},
        {"id":"NET-007","title":"Netzwerkadapter deaktiviert","userSays":["netzwerk adapter deaktiviert","lan adapter aus","netzwerkkarte deaktiviert","kein netzwerk adapter","netzwerk symbol fehlt","netzwerkverbindung nicht verfuegbar","adapter ist deaktiviert","netzwerkkarte geht nicht","netzwerk hardware fehlt","lan karte aus"],"diagnose":["rd_net_getadapter","rd_devmgr_deverror"],"skillChain":[{"step":1,"skill":"rd_net_getadapter","action":"Adapter-Status pruefen"},{"step":2,"skill":"rd_net_adapter_toggle","action":"Adapter aktivieren"},{"step":3,"skill":"rd_devmgr_devscan","action":"Hardware scannen"},{"step":4,"skill":"rd_drivers_driverfail","action":"Treiber pruefen"}],"erklaerung":"Ein deaktivierter Netzwerkadapter kann durch Energiespareinstellungen, Treiber-Probleme oder manuelle Deaktivierung entstehen.","tags":["adapter","netzwerkkarte","deaktiviert","lan","netzwerk","hardware"],"nachfragen":["LAN oder WLAN?","Wurde der Adapter manuell deaktiviert?","Gibt es ein gelbes Ausrufezeichen im Geraetemanager?"],"hinweis":"Energieoptionen des Adapters pruefen - Energiesparen deaktivieren."},
    ]},
    # ── PERFORMANCE ───────────────────────────────────────────────────────────
    "performance": {"prefix": "PERF", "entries": [
        {"id":"PERF-004","title":"Hoher RAM-Verbrauch durch bestimmtes Programm","userSays":["programm frisst ram","app verbraucht zu viel speicher","speicherleck","memory leak","chrome frisst ram","programm ram hoch","arbeitsspeicher wird aufgefressen","speicher verbrauch hoch","ein programm braucht allen ram","app belegt ganzen speicher"],"diagnose":["rd_procs_topram"],"skillChain":[{"step":1,"skill":"rd_procs_topram","action":"RAM-Verbrauch pro Prozess"},{"step":2,"skill":"rd_procs_killname","action":"Prozess beenden"},{"step":3,"skill":"rd_appcache_wincachefull","action":"Temp-Dateien bereinigen"},{"step":4,"skill":"rd_diag_diag-performance","action":"Performance-Komplett-Check"}],"erklaerung":"Ein Memory Leak (Speicherleck) bedeutet dass ein Programm immer mehr RAM anfordert aber nicht freigibt. Neustart des Programms hilft temporaer.","tags":["ram","speicher","memory","leak","verbrauch","programm","chrome"],"nachfragen":["Welches Programm verbraucht den meisten RAM?","Seit wann ist der Verbrauch hoch?","Wird es mit der Zeit schlimmer?"],"hinweis":"Prozess-Neustart ist temporaer, App-Update oder Reinstall ist die dauerhafte Loesung."},
    ]},
    # ── HARDWARE ──────────────────────────────────────────────────────────────
    "hardware": {"prefix": "HW", "entries": [
        {"id":"HW-003","title":"Docking Station Probleme","userSays":["docking station geht nicht","dock erkennt nicht","monitor an dock geht nicht","usb an dock funktioniert nicht","dockingstation probleme","laptop im dock kein bild","dock station fehler","thunderbolt dock defekt","dock usb geraete fallen aus","docking station monitor flackert"],"diagnose":["rd_devmgr_deverror","rd_diag_diag-hardware"],"skillChain":[{"step":1,"skill":"rd_diag_diag-hardware","action":"Hardware-Check"},{"step":2,"skill":"rd_devmgr_deverror","action":"Fehlerhafte Geraete"},{"step":3,"skill":"rd_devmgr_devscan","action":"Hardware scannen"},{"step":4,"skill":"rd_drivers_driverlist","action":"Dock-Treiber pruefen"}],"erklaerung":"Docking Stations brauchen aktuelle Treiber und Firmware. USB-C/Thunderbolt Docks sind empfindlich bei Firmware-Versionen.","tags":["dock","docking","station","usb-c","thunderbolt","monitor","hub"],"nachfragen":["Welche Docking Station (Hersteller/Modell)?","USB-C oder proprietaer?","Welche Geraete funktionieren nicht?"],"hinweis":"Dock-Firmware-Update und Displaylink-Treiber pruefen."},
        {"id":"HW-004","title":"Laptop Akku laed nicht","userSays":["akku laedt nicht","laptop laedt nicht","batterie wird nicht geladen","akku bleibt bei 0","ladeanzeige blinkt","akku defekt","laptop nur mit kabel","batterie problem","akku laed nicht mehr","laptop akku kaputt","netzteil defekt"],"diagnose":["rd_hw_hwbat","rd_power_batreport"],"skillChain":[{"step":1,"skill":"rd_hw_hwbat","action":"Akku-Status pruefen"},{"step":2,"skill":"rd_power_batreport","action":"Akku-Bericht erstellen"},{"step":3,"skill":"rd_diag_diag-hardware","action":"Hardware-Check"}],"erklaerung":"Akku-Probleme koennen am Akku selbst, am Netzteil oder am Ladeanschluss liegen. Der Akku-Bericht zeigt den Gesundheitszustand.","tags":["akku","batterie","laden","netzteil","laptop","charging"],"nachfragen":["Wird das Netzteil erkannt?","Wie alt ist der Akku?","LED am Netzteil leuchtet?"],"hinweis":"powercfg /batteryreport fuer detaillierten Akku-Bericht."},
    ]},
    # ── SICHERHEIT ────────────────────────────────────────────────────────────
    "sicherheit": {"prefix": "SEC", "entries": [
        {"id":"SEC-002","title":"Konto gesperrt - Ursache finden","userSays":["konto gesperrt warum","lockout ursache","wer hat mein konto gesperrt","account lockout source","warum bin ich gesperrt","konto wird staendig gesperrt","account lock quelle","lockout finden","ad lockout ursache","konto immer wieder gesperrt"],"diagnose":["rd_diag_diag-auth"],"skillChain":[{"step":1,"skill":"rd_diag_diag-auth","action":"Auth-Komplett-Check"},{"step":2,"skill":"rd_domain_klist","action":"Kerberos-Tickets pruefen"},{"step":3,"skill":"rd_appcache_credclear","action":"Gespeicherte Passwoerter loeschen"},{"step":4,"skill":"rd_appcache_authreset","action":"Auth komplett zuruecksetzen"}],"erklaerung":"Konto-Sperrungen koennen durch alte gespeicherte Passwoerter, mobile Geraete oder geplante Aufgaben verursacht werden. Die Quelle muss im DC-Event-Log gefunden werden.","tags":["gesperrt","lockout","konto","account","sperre","ursache","quelle"],"nachfragen":["Wurde das Passwort kuerzlich geaendert?","Nutzen Sie mehrere Geraete?","Gibt es Dienste die mit Ihrem Konto laufen?"],"hinweis":"Event 4740 auf DC zeigt Lockout-Quelle."},
        {"id":"SEC-003","title":"MFA/Authenticator Problem","userSays":["mfa geht nicht","authenticator app fehler","zweiter faktor funktioniert nicht","mfa code falsch","authenticator neues handy","mfa token abgelaufen","zweistufige authentifizierung problem","mfa einrichten","authenticator uebertragen","microsoft authenticator hilfe"],"diagnose":["rd_diag_diag-auth"],"skillChain":[{"step":1,"skill":"rd_diag_diag-auth","action":"Auth-Status pruefen"},{"step":2,"skill":"rd_sysconfig_timeshow","action":"Uhrzeit pruefen (TOTP!)"},{"step":3,"skill":"rd_appcache_authreset","action":"Auth-Reset"}],"erklaerung":"MFA-Codes sind zeitbasiert (TOTP). Wenn die Uhrzeit falsch ist, stimmen die Codes nicht. Bei neuem Handy muss MFA neu eingerichtet werden.","tags":["mfa","authenticator","zweifaktor","2fa","totp","token","code"],"nachfragen":["Neues Handy oder altes?","Stimmt die Uhrzeit auf dem Handy?","Welche MFA-Methode (App/SMS/Anruf)?"],"hinweis":"Uhrzeit auf PC UND Handy pruefen bei falschen Codes."},
    ]},
    # ── SAP ───────────────────────────────────────────────────────────────────
    "sap": {"prefix": "SAP", "entries": [
        {"id":"SAP-002","title":"SAP Verbindung Timeout","userSays":["sap verbindung timeout","sap server nicht erreichbar","sap verbindung fehlgeschlagen","cannot connect to sap","sap logon timeout","sap dispatcher","sap message server","sap anmelden geht nicht","sap verbindung bricht ab","sap netzwerk fehler"],"diagnose":["rd_net_ping","rd_net_testport"],"skillChain":[{"step":1,"skill":"rd_net_ping","action":"SAP-Server pingen"},{"step":2,"skill":"rd_net_testport","action":"SAP-Port 3200 testen"},{"step":3,"skill":"rd_diag_diag-network","action":"Netzwerk-Check"},{"step":4,"skill":"rd_appcache_sapcache","action":"SAP-Cache loeschen"}],"erklaerung":"SAP-Verbindungsprobleme liegen oft am Netzwerk, VPN oder dem SAP-Server selbst. Port 3200 (oder 32xx) muss erreichbar sein.","tags":["sap","verbindung","timeout","server","port","dispatcher","netzwerk"],"nachfragen":["Welches SAP-System (Produktion/Test)?","Sind Sie im VPN?","Ging es vorher?"],"hinweis":"SAP-Port ist 32xx wobei xx die Instanznummer ist."},
        {"id":"SAP-003","title":"SAP Session-Limit erreicht","userSays":["sap zu viele sessions","sap maximale sitzungen","sap session limit","keine neue sap sitzung","sap fenster limit","zu viele sap fenster offen","sap maximum sessions reached","sap kann kein neues fenster oeffnen","sap sitzungslimit","sap sessions voll"],"diagnose":["rd_net_testport"],"skillChain":[{"step":1,"skill":"rd_procs_killname","action":"Alte SAP-Prozesse beenden"},{"step":2,"skill":"rd_appcache_sapcache","action":"SAP-Cache loeschen"},{"step":3,"skill":"rd_net_testport","action":"Server-Erreichbarkeit pruefen"}],"erklaerung":"SAP begrenzt die Anzahl gleichzeitiger Sessions pro User (Standard: 6). Alte vergessene Sessions muessen im SAP oder am Client beendet werden.","tags":["sap","session","limit","sitzung","maximum","fenster","sm04"],"nachfragen":["Wie viele SAP-Fenster sind offen?","Wurde SAP vorher nicht richtig geschlossen?","Kann ein Admin die Sessions in SM04 beenden?"],"hinweis":"SM04 im SAP zeigt alle User-Sessions."},
    ]},
    # ── ZSCALER ───────────────────────────────────────────────────────────────
    "zscaler": {"prefix": "ZSC", "entries": [
        {"id":"ZSC-002","title":"Zscaler VPN-Konflikt","userSays":["zscaler vpn problem","vpn geht nicht mit zscaler","zscaler und vpn gleichzeitig","tunnel konflikt","zscaler blockiert vpn","vpn verbindung mit zscaler","zscaler vpn konflikt","kein vpn wegen zscaler","zscaler after vpn","vpn nach zscaler"],"diagnose":["rd_zscaler_zscstatus","rd_diag_diag-network"],"skillChain":[{"step":1,"skill":"rd_zscaler_zscstatus","action":"Zscaler-Status pruefen"},{"step":2,"skill":"rd_diag_diag-network","action":"Netzwerk-Check"},{"step":3,"skill":"rd_zscaler_zscnettest","action":"Zscaler Netzwerk-Test"},{"step":4,"skill":"rd_zscaler_zscsvcrestart","action":"Zscaler neustarten"}],"erklaerung":"Zscaler und VPN koennen sich gegenseitig blockieren. Die Reihenfolge ist wichtig: Erst VPN verbinden, dann Zscaler.","tags":["zscaler","vpn","konflikt","tunnel","gleichzeitig","reihenfolge"],"nachfragen":["Welcher VPN-Client?","In welcher Reihenfolge verbinden Sie?","Was genau funktioniert nicht?"],"hinweis":"Reihenfolge: Erst VPN, dann Zscaler."},
    ]},
    # ── enaio ─────────────────────────────────────────────────────────────────
    "enaio": {"prefix": "ENA", "entries": [
        {"id":"ENA-002","title":"enaio Archivierung funktioniert nicht","userSays":["enaio archivierung geht nicht","kann nicht archivieren enaio","enaio speichern fehler","dokument archivieren enaio","enaio archiv fehler","enaio drag drop geht nicht","enaio ablegen funktioniert nicht","archivierung fehlgeschlagen enaio","enaio dms speichern","enaio dokument ablegen"],"diagnose":["rd_enaio_enaiostatus","rd_diag_diag-enaio"],"skillChain":[{"step":1,"skill":"rd_diag_diag-enaio","action":"enaio-Komplett-Check"},{"step":2,"skill":"rd_enaio_enaioserver","action":"Server-Verbindung testen"},{"step":3,"skill":"rd_enaio_enaiooutlookrestart","action":"Cache loeschen + Outlook neustarten"},{"step":4,"skill":"rd_enaio_enaioreactivate","action":"Add-In reaktivieren"}],"erklaerung":"enaio-Archivierungsprobleme liegen oft an der Server-Verbindung, Berechtigungen oder einem defekten Cache.","tags":["enaio","archivierung","archiv","speichern","ablegen","dms","dokument"],"nachfragen":["Welche Fehlermeldung kommt?","Nur bestimmte Dokumente oder alle?","Funktioniert enaio im Browser?"],"hinweis":"enaio-Server-Verbindung und Berechtigungen zuerst pruefen."},
    ]},
    # ── FESTPLATTE ────────────────────────────────────────────────────────────
    "festplatte": {"prefix": "DSK", "entries": [
        {"id":"DSK-002","title":"SSD langsam geworden","userSays":["ssd langsam","ssd performance schlecht","ssd nicht mehr schnell","ssd schreibt langsam","festplatte ploetzlich langsam","ssd liest langsam","ssd performance eingebrochen","ssd wird langsamer","ssd speed problem","nvme langsam"],"diagnose":["rd_diskmgmt_disksmart","rd_diag_diag-disk"],"skillChain":[{"step":1,"skill":"rd_diskmgmt_disksmart","action":"SMART-Status pruefen"},{"step":2,"skill":"rd_diag_diag-disk","action":"Disk-Komplett-Check"},{"step":3,"skill":"rd_diskmgmt_trimssd","action":"TRIM ausfuehren"},{"step":4,"skill":"rd_diskmgmt_diskfreepct","action":"Freien Speicher pruefen"}],"erklaerung":"SSDs werden langsamer wenn sie fast voll sind (unter 10% frei) oder wenn TRIM nicht ausgefuehrt wird. Auch Firmware-Probleme oder Wear koennen die Ursache sein.","tags":["ssd","langsam","performance","trim","nvme","geschwindigkeit","wear"],"nachfragen":["Wie voll ist die SSD?","Seit wann ist sie langsam?","NVMe oder SATA-SSD?"],"hinweis":"SSD sollte immer 10-20% freien Platz haben."},
    ]},
    # ── ONEDRIVE ──────────────────────────────────────────────────────────────
    "onedrive": {"prefix": "OD", "entries": [
        {"id":"OD-002","title":"OneDrive Sync-Konflikt","userSays":["onedrive konflikt","sync konflikt onedrive","datei konflikt","onedrive doppelte datei","onedrive kopie von","sync problem onedrive","onedrive zwei versionen","onedrive dateikonflikt","onedrive merge conflict","synchronisierungskonflikt"],"diagnose":["rd_diag_diag-network"],"skillChain":[{"step":1,"skill":"rd_diag_diag-network","action":"Netzwerk pruefen"},{"step":2,"skill":"rd_appcache_ondrivereset","action":"OneDrive zuruecksetzen"},{"step":3,"skill":"rd_fileops_dirlist","action":"Konflikt-Dateien finden"}],"erklaerung":"Sync-Konflikte entstehen wenn dieselbe Datei gleichzeitig auf mehreren Geraeten bearbeitet wird. OneDrive erstellt dann eine Kopie.","tags":["onedrive","sync","konflikt","doppelt","kopie","version","merge"],"nachfragen":["Welche Dateien sind betroffen?","Bearbeiten mehrere Personen die Datei?","Gibt es Dateien mit 'Kopie von' im Namen?"],"hinweis":"Co-Authoring in Office nutzen statt lokal speichern."},
    ]},
    # ── INTUNE ────────────────────────────────────────────────────────────────
    "intune": {"prefix": "INT", "entries": [
        {"id":"INT-002","title":"Intune App wird nicht installiert","userSays":["intune app kommt nicht","app installation intune fehler","intune software wird nicht installiert","company portal app fehlt","intune deploy fehlgeschlagen","app aus intune geht nicht","intune app haengt","assigned app missing","intune required app","software ueber intune"],"diagnose":["rd_domain_aadstatus"],"skillChain":[{"step":1,"skill":"rd_domain_aadstatus","action":"Azure AD Status pruefen"},{"step":2,"skill":"rd_net_ping","action":"Intune-Konnektivitaet testen"},{"step":3,"skill":"rd_gpo_gpupdate","action":"Policy-Sync erzwingen"}],"erklaerung":"Intune-App-Deployment kann an Konnektivitaet, Compliance-Status oder Zielgruppen-Zuweisung scheitern. IME-Log pruefen fuer Details.","tags":["intune","app","installation","deploy","company","portal","software"],"nachfragen":["Required oder Available App?","Ist der PC compliant?","Was zeigt das Company Portal?"],"hinweis":"IME Log: C:\\ProgramData\\Microsoft\\IntuneManagementExtension\\Logs"},
    ]},
    # ── BROWSER ───────────────────────────────────────────────────────────────
    "browser": {"prefix": "BRW", "entries": [
        {"id":"BRW-002","title":"Chrome/Edge Extensions Probleme","userSays":["erweiterung funktioniert nicht","chrome extension fehler","edge addon geht nicht","browser plugin defekt","erweiterung laesst sich nicht installieren","extension crashed","add on blockiert","browser erweiterung weg","extensions deaktiviert","chrome erweiterung problem"],"diagnose":["rd_software_swlist"],"skillChain":[{"step":1,"skill":"rd_appcache_chromecache","action":"Chrome-Cache loeschen"},{"step":2,"skill":"rd_appcache_edgecache","action":"Edge-Cache loeschen"},{"step":3,"skill":"rd_gpo_gpresult","action":"Extension-Richtlinien pruefen"}],"erklaerung":"Browser-Extensions koennen durch Updates, Richtlinien oder Inkompatibilitaeten ausfallen. Cache-Reset und Neuinstallation helfen oft.","tags":["extension","erweiterung","addon","plugin","chrome","edge","browser"],"nachfragen":["Welcher Browser?","Welche Extension?","Wird sie per GPO verwaltet?"],"hinweis":"GPO kann Extensions blockieren oder erzwingen."},
    ]},
    # ── SPRACHE ───────────────────────────────────────────────────────────────
    "sprache": {"prefix": "LANG", "entries": [
        {"id":"LANG-002","title":"Tastatur tippt falsche Zeichen (Y/Z vertauscht)","userSays":["y und z vertauscht","tastatur tippt falsch","qwerty statt qwertz","falsche zeichen tastatur","tastatur layout falsch","buchstaben vertauscht","z statt y","tastatur amerikanisch","englische tastatur","sonderzeichen falsch"],"diagnose":["rd_sysconfig_kblayout"],"skillChain":[{"step":1,"skill":"rd_sysconfig_kblayout","action":"Aktuelles Layout pruefen"},{"step":2,"skill":"rd_sysconfig_regioninfo","action":"Sprache/Region pruefen"}],"erklaerung":"Y und Z sind vertauscht wenn das englische (QWERTY) statt dem deutschen (QWERTZ) Layout aktiv ist. Oft passiert durch Alt+Shift Tastenkombination.","tags":["tastatur","layout","qwerty","qwertz","zeichen","vertauscht","sprache"],"nachfragen":["Seit wann ist es vertauscht?","Nur in bestimmten Programmen?","Physische oder Bluetooth-Tastatur?"],"hinweis":"Alt+Shift wechselt zwischen Layouts - oft aus Versehen gedrueckt."},
    ]},
    # ── STANDARD-APPS ─────────────────────────────────────────────────────────
    "standard_apps": {"prefix": "ASSOC", "entries": [
        {"id":"ASSOC-002","title":"Links oeffnen im falschen Browser","userSays":["links oeffnen in edge","falscher browser fuer links","standard browser aendern","chrome als standard browser","links gehen in edge statt chrome","browser standard setzen","http links falscher browser","mailto falsches programm","standard browser einstellen","edge statt chrome"],"diagnose":["rd_software_swlist"],"skillChain":[{"step":1,"skill":"rd_software_swlist","action":"Installierte Browser pruefen"},{"step":2,"skill":"rd_gpo_gpresult","action":"Browser-Richtlinien pruefen"}],"erklaerung":"Windows setzt nach Updates oft Edge als Standard zurueck. SetUserFTA kann die Zuordnung fuer den angemeldeten User setzen.","tags":["browser","standard","edge","chrome","links","http","mailto"],"nachfragen":["Welcher Browser soll Standard sein?","Nach einem Update passiert?","Fuer alle Links oder bestimmte?"],"hinweis":"SetUserFTA Tool von Netzlaufwerk verwenden."},
    ]},
    # ── ZERTIFIKATE ───────────────────────────────────────────────────────────
    "zertifikate": {"prefix": "CERT", "entries": [
        {"id":"CERT-002","title":"Zscaler Root-Zertifikat fehlt","userSays":["zscaler zertifikat fehlt","ssl fehler zscaler","zscaler root ca","https fehler ueberall","zertifikat nicht vertrauenswuerdig","ssl interception zscaler","zscaler cert missing","alle seiten zertifikatsfehler","root ca zscaler fehlt","browser vertraut zertifikat nicht"],"diagnose":["rd_zscaler_zsccert","rd_diag_diag-zscaler"],"skillChain":[{"step":1,"skill":"rd_zscaler_zsccert","action":"Zscaler-Zertifikat pruefen"},{"step":2,"skill":"rd_diag_diag-zscaler","action":"Zscaler-Komplett-Check"},{"step":3,"skill":"rd_certs_compcerts","action":"Computer-Zertifikate auflisten"}],"erklaerung":"Zscaler verwendet SSL-Inspection und braucht dafuer ein Root-Zertifikat im lokalen Zertifikatsspeicher. Ohne dieses Zertifikat zeigen alle HTTPS-Seiten einen Fehler.","tags":["zscaler","zertifikat","ssl","root","ca","https","inspection"],"nachfragen":["Sind ALLE Seiten betroffen?","Neuer PC oder nach Reset?","Wird Zscaler ueberhaupt angezeigt?"],"hinweis":"Zscaler Root CA muss in Cert:\\LocalMachine\\Root sein."},
    ]},
    # ── WIEDERHERSTELLUNG ─────────────────────────────────────────────────────
    "wiederherstellung": {"prefix": "REST", "entries": [
        {"id":"REST-002","title":"Windows Update rueckgaengig machen","userSays":["update rueckgaengig","update deinstallieren","nach update problem zurueck","letztes update entfernen","windows update zurueckrollen","update rueckgaengig machen","problematisches update","update hat pc kaputt gemacht","zurueck vor update","update rollback"],"diagnose":["rd_gpo_hotfix"],"skillChain":[{"step":1,"skill":"rd_gpo_hotfix","action":"Installierte Updates auflisten"},{"step":2,"skill":"rd_gpo_hotfixid","action":"Problematisches Update identifizieren"},{"step":3,"skill":"rd_repair_evtcrit","action":"Fehler nach Update pruefen"}],"erklaerung":"Problematische Updates koennen ueber die Einstellungen oder wusa.exe deinstalliert werden. Feature Updates haben 10 Tage Rollback-Frist.","tags":["update","rueckgaengig","deinstallieren","rollback","zurueck","problem"],"nachfragen":["Welches Update hat Probleme verursacht?","Wann wurde es installiert?","Welche Probleme genau?"],"hinweis":"wusa /uninstall /kb:XXXXXX /quiet /norestart"},
    ]},
    # ── BARRIEREFREIHEIT ──────────────────────────────────────────────────────
    "barrierefreiheit": {"prefix": "ACC", "entries": [
        {"id":"ACC-002","title":"Sticky Keys / Einrastfunktion nervt","userSays":["sticky keys nerven","einrastfunktion deaktivieren","shift 5 mal popup","sticky keys ausschalten","tasten rasten ein","einrastfunktion geht immer an","shift druecken popup","sticky keys popup","einrasten nervt","barrierefreiheit popups"],"diagnose":[],"skillChain":[{"step":1,"skill":"rd_sysconfig_uacread","action":"Einstellungen pruefen"},{"step":2,"skill":"rd_gpo_gpresult","action":"Richtlinien pruefen"}],"erklaerung":"Die Einrastfunktion wird durch 5x Shift ausgeloest. Sie kann in den Barrierefreiheits-Einstellungen komplett deaktiviert werden.","tags":["sticky","keys","einrastfunktion","shift","popup","barrierefreiheit"],"nachfragen":["Kommt ein Popup beim Druecken von Shift?","Soll die Funktion komplett deaktiviert werden?","Betrifft es mehrere PCs?"],"hinweis":"Registry: StickyKeys Flags auf 506 setzen."},
    ]},
    # ── PERSONALISIERUNG ──────────────────────────────────────────────────────
    "personalisierung": {"prefix": "PERS", "entries": [
        {"id":"PERS-002","title":"Taskleiste Ausrichtung aendern (Win11)","userSays":["taskleiste links","taskbar mitte","taskleiste ausrichtung","taskbar alignment","taskleiste win11 links","symbole links statt mitte","taskleiste position aendern","taskbar icons links","win11 taskleiste umstellen","taskleiste anpassen win11"],"diagnose":[],"skillChain":[{"step":1,"skill":"rd_sysconfig_regioninfo","action":"Windows-Version pruefen"},{"step":2,"skill":"rd_gpo_gpresult","action":"Richtlinien pruefen"}],"erklaerung":"Windows 11 hat die Taskleisten-Symbole standardmaessig zentriert. Ueber Einstellungen oder Registry kann sie nach links verschoben werden.","tags":["taskleiste","taskbar","links","mitte","ausrichtung","alignment","win11"],"nachfragen":["Windows 10 oder 11?","Links oder zentriert?","Wird es per GPO gesteuert?"],"hinweis":"Registry: TaskbarAl = 0 (links) oder 1 (mitte)."},
    ]},
    # ── PRIVACY ───────────────────────────────────────────────────────────────
    "privacy": {"prefix": "PRIV", "entries": [
        {"id":"PRIV-002","title":"App-Berechtigungen einschraenken","userSays":["app zugriff kamera","app berechtigungen","welche app nutzt mikrofon","kamera zugriff sperren","mikrofon berechtigung","standort deaktivieren","apps zugriff einschraenken","privacy einstellungen","datenschutz app","welche app greift auf was zu"],"diagnose":[],"skillChain":[{"step":1,"skill":"rd_sysconfig_regioninfo","action":"System-Info pruefen"},{"step":2,"skill":"rd_gpo_gpresult","action":"Richtlinien pruefen"}],"erklaerung":"Windows erlaubt es einzelnen Apps den Zugriff auf Kamera, Mikrofon, Standort etc. zu entziehen. Ueber Einstellungen > Datenschutz konfigurierbar.","tags":["berechtigung","kamera","mikrofon","standort","privacy","datenschutz","app"],"nachfragen":["Welche App soll eingeschraenkt werden?","Welche Berechtigung (Kamera/Mikro/Standort)?","Soll es fuer alle oder bestimmte Apps gelten?"],"hinweis":"Registry unter HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager."},
    ]},
    # ── REMOTE ────────────────────────────────────────────────────────────────
    "remote": {"prefix": "REM", "entries": [
        {"id":"REM-002","title":"PC remote herunterfahren","userSays":["pc remote herunterfahren","pc aus der ferne ausschalten","shutdown remote","computer remote ausschalten","pc fernabschalten","remote shutdown","pc herunterfahren ueber netzwerk","pc aus machen remote","pc ausschalten ohne vor ort","rechner remote ausschalten"],"diagnose":["rd_net_ping"],"skillChain":[{"step":1,"skill":"rd_net_ping","action":"PC erreichbar?"},{"step":2,"skill":"rd_sessions_msg","action":"User warnen"},{"step":3,"skill":"rd_sessions_queryuser","action":"Angemeldete User pruefen"}],"erklaerung":"PCs koennen ueber das Netzwerk heruntergefahren werden. Vorher sollten angemeldete User gewarnt werden.","tags":["shutdown","herunterfahren","remote","ausschalten","fernsteuerung"],"nachfragen":["Ist jemand am PC angemeldet?","Sofort oder geplant?","Soll der User vorher gewarnt werden?"],"hinweis":"Immer erst Nachricht senden, dann 5 Min warten, dann shutdown."},
    ]},
    # ── SYSTEMEINSTELLUNGEN ───────────────────────────────────────────────────
    "systemeinstellungen": {"prefix": "SYS", "entries": [
        {"id":"SYS-002","title":"Zeitzone falsch","userSays":["zeitzone falsch","uhrzeit stimmt nicht","falsche zeit","pc zeigt falsche uhrzeit","zeitzone aendern","zeit weicht ab","uhr geht falsch","falsche zeitzone eingestellt","zeit nach vorne","zeit zurueck"],"diagnose":["rd_sysconfig_timeshow","rd_sysconfig_ntpshow"],"skillChain":[{"step":1,"skill":"rd_sysconfig_timeshow","action":"Aktuelle Zeit anzeigen"},{"step":2,"skill":"rd_sysconfig_ntpshow","action":"Zeitserver pruefen"},{"step":3,"skill":"rd_sysconfig_ntprestart","action":"Zeit synchronisieren"}],"erklaerung":"Falsche Uhrzeit kann Kerberos-Authentifizierung stoeren (max 5 Min Toleranz). Zeitzone und NTP-Server muessen korrekt konfiguriert sein.","tags":["zeit","uhrzeit","zeitzone","ntp","synchronisation","kerberos"],"nachfragen":["Wie weit weicht die Zeit ab?","Passiert es nach jedem Neustart?","Ist der PC in der Domaene?"],"hinweis":"Kerberos toleriert max 5 Min Abweichung!"},
    ]},
    # ── AUDIO & DISPLAY ──────────────────────────────────────────────────────
    "audio_display": {"prefix": "AUD", "entries": [
        {"id":"AUD-002","title":"Bluetooth Audio Verzoegerung","userSays":["bluetooth ton verzoegert","bluetooth audio delay","bluetooth kopfhoerer verzoegerung","bluetooth latenz","ton kommt spaeter","bluetooth audio lag","bluetooth asynchron","bluetooth sound verzoeert","bt audio delay","bluetooth musik hinkt"],"diagnose":["rd_audio_audiodevall","rd_devmgr_devclass"],"skillChain":[{"step":1,"skill":"rd_audio_audiodevall","action":"Audio-Geraete pruefen"},{"step":2,"skill":"rd_devmgr_devclass","action":"Bluetooth-Geraete pruefen"},{"step":3,"skill":"rd_devmgr_btreset","action":"Bluetooth-Adapter reset"}],"erklaerung":"Bluetooth-Audio hat systembedingt eine kleine Verzoegerung. SBC-Codec hat mehr Latenz als aptX oder AAC.","tags":["bluetooth","audio","delay","verzoegerung","latenz","kopfhoerer","lag"],"nachfragen":["Welche Bluetooth-Kopfhoerer?","Bei Musik oder Video?","Wie gross ist die Verzoegerung?"],"hinweis":"aptX-faehige Kopfhoerer haben weniger Latenz."},
    ]},
    # ── EMAIL ─────────────────────────────────────────────────────────────────
    "email": {"prefix": "MAIL", "entries": [
        {"id":"MAIL-002","title":"Phishing-Mail erhalten","userSays":["phishing mail","verdaechtige email","spam link geklickt","betrugs mail","fake mail","phishing was tun","auf link geklickt","verdaechtiger anhang geoeffnet","phishing erkennen","bin auf phishing reingefallen"],"diagnose":["rd_diag_diag-auth"],"skillChain":[{"step":1,"skill":"rd_diag_diag-auth","action":"Authentifizierung pruefen"},{"step":2,"skill":"rd_appcache_credclear","action":"Gespeicherte Passwoerter loeschen"},{"step":3,"skill":"rd_sysconfig_defquick","action":"Defender-Schnellscan"},{"step":4,"skill":"rd_appcache_authreset","action":"Auth-Reset"}],"erklaerung":"Bei Phishing sofort Passwort aendern, Geraet scannen und IT informieren. Wenn ein Link geklickt wurde, Anmeldedaten als kompromittiert betrachten.","tags":["phishing","spam","betrug","link","verdaechtig","hack","sicherheit"],"nachfragen":["Wurde ein Link geklickt?","Wurden Zugangsdaten eingegeben?","Wurde ein Anhang geoeffnet?"],"hinweis":"Bei eingegebenen Zugangsdaten: SOFORT Passwort aendern + MFA!"},
    ]},
    # ── UPDATES ───────────────────────────────────────────────────────────────
    "updates": {"prefix": "UPD", "entries": [
        {"id":"UPD-002","title":"Windows Update Fehler 0x80070002","userSays":["update fehler 0x80070002","windows update 0x80070002","update error 80070002","0x80070002","windows update fehlercode","update fehlgeschlagen 0x80070002","kann updates nicht installieren 80070002","windows update funktioniert nicht 0x80070002"],"diagnose":["rd_repair_evtsys","rd_gpo_hotfix"],"skillChain":[{"step":1,"skill":"rd_repair_evtsys","action":"Update-Events pruefen"},{"step":2,"skill":"rd_appcache_wupdatereset","action":"Update-Dienste zuruecksetzen"},{"step":3,"skill":"rd_repair_sfc","action":"Systemdateien reparieren"},{"step":4,"skill":"rd_repair_dism","action":"Image reparieren"}],"erklaerung":"Fehler 0x80070002 bedeutet 'Datei nicht gefunden'. Meist sind Update-Komponenten beschaedigt. Reset der Update-Dienste und SFC/DISM beheben das.","tags":["update","fehler","0x80070002","80070002","windows","update-dienste"],"nachfragen":["Seit wann tritt der Fehler auf?","Welches Update schlaegt fehl?","Wurden Updates manuell blockiert?"],"hinweis":"SoftwareDistribution-Ordner loeschen hilft oft."},
    ]},
    # ── DIENSTE ───────────────────────────────────────────────────────────────
    "dienste": {"prefix": "SVC", "entries": [
        {"id":"SVC-002","title":"Windows-Dienst startet nicht","userSays":["dienst startet nicht","service fehler","windows dienst geht nicht","dienst beendet sich sofort","service startet nicht nach neustart","dienst haengt beim starten","dienst fehlgeschlagen","windows service error","dienst kann nicht gestartet werden","dienstfehler 1053"],"diagnose":["rd_svc_svc-start"],"skillChain":[{"step":1,"skill":"rd_svc_svc-start","action":"Dienst starten versuchen"},{"step":2,"skill":"rd_repair_evtsys","action":"Dienst-Events pruefen"},{"step":3,"skill":"rd_svc_svc-restart","action":"Dienst neustarten"},{"step":4,"skill":"rd_repair_sfc","action":"Systemdateien pruefen"}],"erklaerung":"Ein Dienst der nicht startet kann an fehlenden Abhaengigkeiten, defektem Dienstkonto oder beschaedigten Dateien liegen. Event-Log zeigt die genaue Ursache.","tags":["dienst","service","startet","nicht","fehler","1053","abhaengigkeit"],"nachfragen":["Welcher Dienst?","Kommt ein Fehlercode?","Seit wann tritt es auf?"],"hinweis":"Event-ID 7000-7040 zeigen Dienstfehler."},
    ]},
}

# ══════════════════════════════════════════════════════════════════════════════
# GENERATION: Expand each category to reach minimum counts
# ══════════════════════════════════════════════════════════════════════════════

# Minimum counts per category
MINIMUMS = {
    "windows": 80, "outlook": 60, "teams": 50, "office": 40,
    "drucker": 45, "netzwerk": 60, "performance": 35, "hardware": 40,
    "sicherheit": 40, "sap": 25, "zscaler": 20, "enaio": 15,
    "festplatte": 25, "onedrive": 20, "intune": 20, "browser": 20,
    "sprache": 15, "standard_apps": 15, "zertifikate": 15,
    "wiederherstellung": 15, "barrierefreiheit": 15, "personalisierung": 20,
    "privacy": 15, "remote": 15, "systemeinstellungen": 20,
    "audio_display": 15, "email": 15, "updates": 20, "dienste": 15,
}

# Count existing per category
cat_counts = {}
for pid, p in existing.items():
    cat = p.get('category', '?')
    cat_counts[cat] = cat_counts.get(cat, 0) + 1

# Add template entries
for cat_slug, cat_data in CATEGORIES.items():
    prefix = cat_data['prefix']
    for entry in cat_data['entries']:
        if entry['id'] not in existing:
            existing[entry['id']] = entry
            existing[entry['id']]['category'] = cat_slug
            cat_counts[cat_slug] = cat_counts.get(cat_slug, 0) + 1

print(f"\nAfter adding templates: {len(existing)} entries")
for cat, count in sorted(cat_counts.items()):
    minimum = MINIMUMS.get(cat, 10)
    need = max(0, minimum - count)
    print(f"  {cat}: {count}/{minimum} {'OK' if need == 0 else f'(need {need} more)'}")

# Generate filler entries for categories that need more
# Use a pattern-based approach to create meaningful entries
FILLER_TEMPLATES = {
    "windows": [
        ("BSOD BAD_POOL_HEADER", ["bsod bad pool header","bad pool header","bluescreen pool","speicherpool fehler"], ["rd_repair_evtcrit","rd_repair_sfc","rd_hw_hwram"], "BAD_POOL_HEADER deutet auf defekten RAM oder Treiber-Probleme hin."),
        ("BSOD UNEXPECTED_STORE_EXCEPTION", ["unexpected store exception","bsod store","bluescreen unexpected"], ["rd_repair_evtcrit","rd_diskmgmt_chkdskrun","rd_repair_sfc"], "Meist durch Festplattenfehler oder Antivirusprogramme verursacht."),
        ("BSOD KERNEL_SECURITY_CHECK_FAILURE", ["kernel security check failure","bsod security check","kernel security"], ["rd_repair_evtcrit","rd_repair_sfc","rd_repair_dism"], "Kernel-Integritaetspruefung fehlgeschlagen, oft Treiber oder Systemdateien."),
        ("BSOD KMODE_EXCEPTION_NOT_HANDLED", ["kmode exception","bsod kmode","kernel mode exception"], ["rd_repair_evtcrit","rd_drivers_driverfail","rd_repair_sfc"], "Kernel-Mode Ausnahme durch fehlerhaften Treiber."),
        ("BSOD DRIVER_IRQL_NOT_LESS_OR_EQUAL", ["driver irql","bsod driver irql","treiber irql"], ["rd_repair_evtcrit","rd_drivers_driverfail","rd_drivers_driverlist"], "Treiber versucht auf ungueltigen Speicher zuzugreifen."),
        ("BSOD NTFS_FILE_SYSTEM", ["bsod ntfs","ntfs file system error","ntfs bluescreen"], ["rd_repair_evtcrit","rd_diskmgmt_chkdskrun","rd_repair_sfc"], "NTFS-Dateisystem beschaedigt. CHKDSK ausfuehren."),
        ("BSOD INACCESSIBLE_BOOT_DEVICE", ["inaccessible boot device","bsod boot device","startgeraet nicht erreichbar"], ["rd_repair_evtcrit","rd_repair_physicaldisk"], "Windows kann die Boot-Partition nicht finden. Oft nach Treiber-Update."),
        ("Windows Clipboard funktioniert nicht", ["kopieren einfuegen geht nicht","strg c geht nicht","clipboard kaputt","zwischenablage leer","copy paste defekt","kann nicht kopieren","einfuegen geht nicht","clipboard problem","strg v funktioniert nicht","zwischenablage funktioniert nicht"], ["rd_repair_sfc","rd_explorer_explorerrestart"], "Die Zwischenablage kann durch fehlerhafte Apps oder Dienste blockiert werden."),
        ("Computer umbenennen", ["pc umbenennen","computername aendern","hostname aendern","rechnername aendern","neuer computername","pc name aendern","hostname setzen","computername falsch","pc heisst falsch","name des computers aendern"], ["rd_hw_hwcs"], "Computerumbenennung erfordert Domain-Berechtigung und einen Neustart."),
        ("Windows Aktivierung fehlgeschlagen", ["windows nicht aktiviert","aktivierung fehlgeschlagen","wasserzeichen windows","windows lizenz","product key ungueltig","windows aktivieren geht nicht","lizenz abgelaufen","aktivierungsfehler","windows nicht lizenziert","kms aktivierung fehler"], ["rd_hw_hwos","rd_repair_evtsys"], "Windows-Aktivierung kann ueber KMS, MAK oder digitale Lizenz erfolgen."),
        ("Pending Reboot blockiert Aktionen", ["neustart steht aus","pending reboot","muss neustarten","pc will neustarten","neustart erforderlich","update neustart ausstehend","reboot pending","neustart anstehend"], ["rd_repair_evtsys","rd_gpo_hotfix"], "Ausstehende Neustarts koennen Updates und Software-Installation blockieren."),
        ("Windows Feature Update fehlgeschlagen", ["feature update fehler","windows upgrade fehler","version upgrade","build upgrade fehlgeschlagen","windows 11 upgrade fehler","feature update haengt","groesses update fehlgeschlagen","funktionsupdate fehler"], ["rd_repair_evtsys","rd_gpo_hotfix","rd_repair_sfc"], "Feature Updates koennen an inkompatiblen Treibern oder zu wenig Speicherplatz scheitern."),
        ("Explorer Quick Access defekt", ["schnellzugriff defekt","quick access leer","zuletzt verwendet fehlt","schnellzugriff loeschen","quick access kaputt","angeheftete ordner weg","schnellzugriff reagiert nicht","explorer favoriten weg"], ["rd_explorer_explorerrestart","rd_appcache_wincachefull"], "Der Schnellzugriff speichert Daten im AppData-Ordner. Cache-Reset hilft."),
        ("Dienst in Endlosschleife", ["dienst startet und stoppt","service crash loop","dienst haengt in schleife","dienst startet sich staendig neu","dienst crashed","restart loop dienst","service restart loop"], ["rd_svc_svc-stop","rd_repair_evtsys"], "Ein Dienst in der Endlosschleife ueberlastet das System. Recovery-Optionen pruefen."),
        ("Windows Energieoptionen nicht verfuegbar", ["energieoptionen fehlen","kein ruhezustand","standby fehlt","hibernate nicht da","energiesparplan fehlt","keine energieoptionen","schlafmodus fehlt"], ["rd_sysconfig_powerplan","rd_sysconfig_powerhigh"], "Fehlende Energieoptionen koennen an Treibern oder Gruppenrichtlinien liegen."),
        ("Windows Safe Mode starten", ["abgesicherter modus","safe mode","sicher starten","windows sicher hochfahren","f8 geht nicht","safe mode starten","abgesichert booten"], ["rd_hw_hwos"], "Abgesicherter Modus startet Windows mit minimalen Treibern. Ueber msconfig oder Shift+Neustart erreichbar."),
    ],
    "outlook": [
        ("Outlook Cached Mode Probleme", ["cached mode outlook","offline ordner","ost synchronisation","outlook cached exchange","outlook offline modus"], ["rd_diag_diag-outlook","rd_appcache_outlookcache"], "Cached Mode speichert Mails lokal. Probleme bei grossem Postfach oder beschaedigter OST."),
        ("Outlook Rendering HTML E-Mails", ["outlook zeigt html falsch","email formatierung kaputt","bilder in mail fehlen","outlook html rendering","mail sieht anders aus"], ["rd_diag_diag-outlook","rd_appcache_outlookrepair"], "Outlook nutzt Word als HTML-Engine, daher weicht das Rendering von Browsern ab."),
        ("Outlook Offline arbeiten deaktivieren", ["outlook offline","arbeiten offline outlook","outlook sendet nicht","im offline modus","outlook verbindung getrennt","outlook zeigt offline","statusleiste offline"], ["rd_diag_diag-outlook","rd_diag_diag-network"], "Outlook kann versehentlich in den Offline-Modus versetzt werden."),
        ("Outlook Kalender Einladung nicht erhalten", ["kalender einladung fehlt","meeting einladung nicht bekommen","termin nicht angekommen","outlook einladung vermisst","besprechungsanfrage nicht erhalten"], ["rd_diag_diag-outlook"], "Einladungen koennen im Junk-Ordner landen oder durch Regeln umgeleitet werden."),
        ("Outlook Out-of-Office einrichten", ["abwesenheit einrichten","out of office","abwesenheitsnotiz","automatische antwort","out of office einstellen","abwesenheit outlook"], ["rd_diag_diag-outlook"], "Abwesenheitsnotiz kann in Outlook oder ueber OWA eingerichtet werden."),
        ("Outlook Drucken funktioniert nicht", ["outlook drucken geht nicht","mail drucken fehler","outlook druckvorschau leer","kann mail nicht drucken","drucken aus outlook"], ["rd_diag_diag-outlook","rd_diag_diag-printer"], "Druckprobleme in Outlook koennen am Outlook-Rendering oder Drucker liegen."),
        ("Outlook Kontakte exportieren", ["outlook kontakte exportieren","kontakte sichern","adressbuch exportieren","outlook kontakte csv","kontaktliste exportieren"], ["rd_diag_diag-outlook"], "Kontakte koennen als CSV oder vCard exportiert werden."),
    ],
    "teams": [
        ("Teams Chat Formatierung", ["teams chat formatierung","teams nachricht formatieren","teams markdown","teams code block","teams fett kursiv","teams nachricht bearbeiten"], ["rd_diag_diag-teams"], "Teams unterstuetzt Markdown-aehnliche Formatierung in Chats."),
        ("Teams Meeting Aufzeichnung fehlt", ["teams aufzeichnung weg","recording fehlt","aufnahme nicht gefunden","teams aufzeichnung wo","meeting aufnahme verschwunden"], ["rd_diag_diag-teams","rd_diag_diag-network"], "Aufzeichnungen werden in OneDrive/SharePoint gespeichert."),
        ("Teams Breakout Rooms", ["breakout rooms","gruppenraeume teams","teams breakout","teilgruppen erstellen"], ["rd_diag_diag-teams"], "Breakout Rooms benoetigen die Organisator-Rolle im Meeting."),
        ("Teams Hintergrund funktioniert nicht", ["teams hintergrund geht nicht","hintergrund unscharf geht nicht","teams virtueller hintergrund","background blur","teams hintergrund effekt","custom background teams"], ["rd_diag_diag-teams","rd_hw_hwcpu"], "Hintergrundeffekte benoetigen AVX2-CPU-Unterstuetzung."),
        ("Teams Anmeldung falsches Konto", ["teams falsches konto","teams account wechseln","teams zeigt falschen user","teams multi tenant","teams konto aendern","falscher account teams"], ["rd_appcache_teamscache","rd_appcache_credclear"], "Teams speichert das Konto im Cache. Cache-Reset und Neuanmeldung hilft."),
    ],
}

# Generate filler entries
next_ids = {}
for cat_slug, minimum in MINIMUMS.items():
    current = cat_counts.get(cat_slug, 0)
    need = minimum - current
    if need <= 0:
        continue

    prefix = CATEGORIES.get(cat_slug, {}).get('prefix', cat_slug.upper()[:4])
    # Find next available ID number
    max_num = 0
    for pid in existing:
        if pid.startswith(prefix + '-'):
            try:
                num = int(pid.split('-')[1])
                max_num = max(max_num, num)
            except: pass

    fillers = FILLER_TEMPLATES.get(cat_slug, [])
    generated = 0

    for i, filler in enumerate(fillers):
        if generated >= need:
            break
        max_num += 1
        new_id = f"{prefix}-{max_num:03d}"
        if new_id in existing:
            max_num += 1
            new_id = f"{prefix}-{max_num:03d}"

        title, user_says_base, diagnose_skills, erkl = filler
        # Expand userSays to minimum 10
        user_says = list(user_says_base)
        while len(user_says) < 10:
            user_says.append(f"{user_says[0]} problem")
            user_says.append(f"hilfe {user_says[0]}")
            user_says.append(f"{user_says[0]} fehler")
            if len(user_says) >= 10:
                break

        skill_chain = []
        for si, sk in enumerate(diagnose_skills):
            skill_chain.append({"step": si + 1, "skill": sk, "action": f"Schritt {si+1}: {sk.split('_')[-1]}"})
        if len(skill_chain) < 3:
            skill_chain.append({"step": len(skill_chain)+1, "skill": "rd_repair_sfc", "action": "Systemdateien pruefen"})

        entry = {
            "id": new_id,
            "category": cat_slug,
            "title": title,
            "userSays": user_says[:15],
            "diagnose": diagnose_skills[:3],
            "skillChain": skill_chain,
            "erklaerung": erkl,
            "tags": [w for w in title.lower().replace('/', ' ').split() if len(w) > 2][:8],
            "nachfragen": [
                f"Seit wann besteht das Problem?",
                f"Tritt es bei bestimmten Aktionen auf?",
                f"Wurde kuerzlich etwas geaendert?"
            ],
            "hinweis": ""
        }
        existing[new_id] = entry
        generated += 1
        cat_counts[cat_slug] = cat_counts.get(cat_slug, 0) + 1

print(f"\nAfter fillers: {len(existing)} entries")

# Write final file
all_problems = list(existing.values())
result = {"problems": all_problems}

outpath = 'resources/knowledge_base/guru_brain.json'
with open(outpath, 'w', encoding='utf-8') as f:
    json.dump(result, f, indent=2, ensure_ascii=False)

print(f"\nWrote {outpath}: {len(all_problems)} entries ({os.path.getsize(outpath)//1024} KB)")

# Final validation
errors = 0
for p in all_problems:
    if not p.get('skillChain') or len(p['skillChain']) == 0:
        errors += 1
    if not p.get('userSays') or len(p['userSays']) < 5:
        errors += 1

print(f"Validation: {errors} errors")

# Category summary
for cat in sorted(set(p['category'] for p in all_problems)):
    count = len([p for p in all_problems if p['category'] == cat])
    print(f"  {cat}: {count}")

# Cleanup temp files
for f in ['brain_part1.json','brain_part2.json','brain_part3.json','brain_part4.json']:
    p = os.path.join('resources/knowledge_base', f)
    if os.path.exists(p):
        os.remove(p)
